'use client';

import { Award, Camera, Edit3, MapPin, Plus, Trash2 } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { AccessibleSheet } from '@/components/ui/AccessibleSheet';
import { authenticatedFetch, readJson } from '@/lib/api';

type Skill = { id: number; name: string; kind: 'teach' | 'learn'; level: string | null };
type Profile = { id: string; email: string | null; display_name: string | null; avatar_url: string | null; bio: string | null; location: string | null; timezone: string | null; skills: Skill[] };

export default function ProfilePage() {
  const [profile, setProfile] = useState<Profile | null>(null);
  const [sheet, setSheet] = useState<'profile' | 'skill' | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [form, setForm] = useState({ displayName: '', bio: '', location: '', timezone: '', avatarUrl: '' });
  const [skill, setSkill] = useState({ name: '', kind: 'teach' as 'teach' | 'learn', level: '' });

  const load = async () => { const data = await authenticatedFetch('/api/profile').then((r) => readJson<{ profile: Profile }>(r)); setProfile(data.profile); setForm({ displayName: data.profile.display_name || '', bio: data.profile.bio || '', location: data.profile.location || '', timezone: data.profile.timezone || '', avatarUrl: data.profile.avatar_url || '' }); };
  useEffect(() => { void load().catch((e) => setError(e instanceof Error ? e.message : 'Unable to load profile')); }, []);
  const displayName = profile?.display_name || 'New user';
  const initials = useMemo(() => displayName.slice(0, 2).toUpperCase(), [displayName]);

  const saveProfile = async () => { try { const data = await authenticatedFetch('/api/profile', { method: 'PATCH', body: JSON.stringify({ displayName: form.displayName, bio: form.bio || null, location: form.location || null, timezone: form.timezone || null, avatarUrl: form.avatarUrl || null }) }).then((r) => readJson<{ profile: Profile }>(r)); setProfile(data.profile); setSheet(null); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save'); } };
  const addSkill = async () => { try { await authenticatedFetch('/api/skills', { method: 'POST', body: JSON.stringify({ name: skill.name, kind: skill.kind, level: skill.level || null }) }).then(readJson); setSkill({ name: '', kind: 'teach', level: '' }); setSheet(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to add skill'); } };
  const removeSkill = async (item: Skill) => { await authenticatedFetch('/api/skills', { method: 'DELETE', body: JSON.stringify({ skillId: Number(item.id), kind: item.kind }) }).then(readJson); await load(); };
  const teach = profile?.skills.filter((s) => s.kind === 'teach') || []; const learn = profile?.skills.filter((s) => s.kind === 'learn') || [];

  return <div className="ss-page ss-page-pad space-y-8 lg:space-y-10">
    <section className="border-b ss-hairline pb-7 lg:pb-9"><div className="h-20 sm:h-28 bg-[var(--signal)] ss-chamfer" /><div className="-mt-8 sm:-mt-10 px-1 sm:px-4 flex flex-col sm:flex-row sm:items-end gap-4 sm:gap-5"><div className="relative w-fit">{profile?.avatar_url ? <img src={profile.avatar_url} alt="" className="h-20 w-20 sm:h-24 sm:w-24 rounded-full border-[5px] border-background object-cover" /> : <div className="h-20 w-20 sm:h-24 sm:w-24 rounded-full border-[5px] border-background bg-foreground text-background grid place-items-center text-xl font-black">{initials}</div>}<button onClick={() => setSheet('profile')} aria-label="Change profile photo" className="absolute -right-1 bottom-1 min-h-11 min-w-11 rounded-full border ss-hairline bg-background grid place-items-center"><Camera className="h-4 w-4" /></button></div><div className="min-w-0 flex-1 pb-1"><h1 className="text-2xl sm:text-3xl truncate">{displayName}</h1><p className="mt-1 text-xs text-muted-foreground truncate">{profile?.email || 'Loading account…'}</p><div className="mt-3 flex flex-wrap items-center gap-2 text-[11px] text-muted-foreground"><span className="inline-flex items-center gap-1"><MapPin className="h-3.5 w-3.5" /> {profile?.location || 'Location not set'}</span>{profile?.timezone && <span className="ss-chip">{profile.timezone}</span>}</div></div><button onClick={() => setSheet('profile')} className="ss-button-primary sm:mb-1"><Edit3 className="h-4 w-4" /> Edit profile</button></div></section>
    {error && <p role="alert" className="text-xs text-red-500">{error}</p>}
    <section className="grid lg:grid-cols-[1fr_300px] gap-8 lg:gap-12"><div className="space-y-9"><div><div className="flex items-center justify-between pb-3 border-b ss-hairline"><div><p className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground font-bold">About</p><h2 className="mt-1">Profile summary</h2></div><button onClick={() => setSheet('profile')} className="min-h-11 min-w-11 grid place-items-center rounded-full hover:bg-muted"><Edit3 className="h-4 w-4" /></button></div><p className="py-6 text-sm text-muted-foreground border-b ss-hairline">{profile?.bio || 'Add a short bio about how you teach, learn and collaborate.'}</p></div><div><div className="flex items-center justify-between pb-3 border-b ss-hairline"><div><p className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground font-bold">Skill exchange</p><h2 className="mt-1">Teach & learn</h2></div><button onClick={() => setSheet('skill')} className="ss-button-secondary"><Plus className="h-4 w-4" /> Add skill</button></div><div className="grid sm:grid-cols-2 border-b ss-hairline"><SkillList title="I can teach" items={teach} remove={removeSkill} /><SkillList title="I want to learn" items={learn} remove={removeSkill} second /></div></div></div><aside><div className="pb-3 border-b ss-hairline"><p className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground font-bold">Achievements</p><h2 className="mt-1">Badges</h2></div><div className="py-8 border-b ss-hairline text-center"><Award className="h-5 w-5 mx-auto text-muted-foreground" /><p className="mt-3 text-xs text-muted-foreground">Badges unlock from completed sessions and appear in Analytics.</p></div></aside></section>
    <AccessibleSheet open={sheet === 'profile'} onClose={() => setSheet(null)} title="Edit profile" description="This information is persisted to your Skill Swap profile."><div className="space-y-3"><input className="ss-input" placeholder="Display name" value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} /><textarea className="ss-input min-h-28 py-3" placeholder="Bio" value={form.bio} onChange={(e) => setForm({ ...form, bio: e.target.value })} /><input className="ss-input" placeholder="Location" value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /><input className="ss-input" placeholder="Timezone, e.g. Asia/Kolkata" value={form.timezone} onChange={(e) => setForm({ ...form, timezone: e.target.value })} /><input className="ss-input" placeholder="Avatar image URL" value={form.avatarUrl} onChange={(e) => setForm({ ...form, avatarUrl: e.target.value })} /><button onClick={saveProfile} className="ss-button-primary w-full">Save profile</button></div></AccessibleSheet>
    <AccessibleSheet open={sheet === 'skill'} onClose={() => setSheet(null)} title="Add a skill" description="Choose whether you can teach it or want to learn it."><div className="space-y-3"><input className="ss-input" placeholder="Skill name" value={skill.name} onChange={(e) => setSkill({ ...skill, name: e.target.value })} /><select className="ss-input" value={skill.kind} onChange={(e) => setSkill({ ...skill, kind: e.target.value as 'teach' | 'learn' })}><option value="teach">I can teach</option><option value="learn">I want to learn</option></select><input className="ss-input" placeholder="Level (optional)" value={skill.level} onChange={(e) => setSkill({ ...skill, level: e.target.value })} /><button disabled={skill.name.trim().length < 2} onClick={addSkill} className="ss-button-primary w-full disabled:opacity-50">Add skill</button></div></AccessibleSheet>
  </div>;
}
function SkillList({ title, items, remove, second = false }: { title: string; items: Skill[]; remove: (s: Skill) => void; second?: boolean }) { return <div className={`py-6 ${second ? 'sm:pl-6 border-t sm:border-t-0' : 'sm:pr-6 sm:border-r'} ss-hairline`}><p className="text-[10px] uppercase tracking-[0.12em] text-muted-foreground font-bold">{title}</p><div className="mt-4 space-y-2">{items.length ? items.map((item) => <div key={`${item.kind}-${item.id}`} className="min-h-11 flex items-center gap-2 border-b ss-hairline"><span className="flex-1 text-xs font-bold">{item.name}{item.level ? <span className="ml-2 text-[10px] text-muted-foreground">{item.level}</span> : null}</span><button onClick={() => remove(item)} className="min-h-11 min-w-11 grid place-items-center" aria-label={`Remove ${item.name}`}><Trash2 className="h-3.5 w-3.5" /></button></div>) : <p className="text-xs text-muted-foreground">No skills added.</p>}</div></div>; }
