'use client';

import { AlertTriangle, Ban, Bug, Mail, PauseCircle, Shield, Trash2 } from 'lucide-react';
import { deleteUser, signOut } from 'firebase/auth';
import { useEffect, useState } from 'react';
import { AccessibleSheet } from '@/components/ui/AccessibleSheet';
import { useAuth } from '@/context/AuthContext';
import { authenticatedFetch, readJson } from '@/lib/api';
import { auth } from '@/lib/firebase';

type Modal = 'delete' | 'deactivate' | 'bug' | 'contact' | 'blocked' | null;
type Block = { id: string; display_name: string | null; avatar_url: string | null; created_at: string };

export default function SettingsPage() {
  const { isDemo, logoutDemo } = useAuth(); const [modal, setModal] = useState<Modal>(null); const [message, setMessage] = useState(''); const [blocks, setBlocks] = useState<Block[]>([]); const [busy, setBusy] = useState(false); const [status, setStatus] = useState<string | null>(null);
  const loadBlocks = () => authenticatedFetch('/api/blocks').then((r) => readJson<{ blocks: Block[] }>(r)).then((data) => setBlocks(data.blocks));
  useEffect(() => { if (!isDemo) void loadBlocks().catch(() => undefined); }, [isDemo]);
  const submitSupport = async (kind: 'bug' | 'contact') => { if (!message.trim()) return; setBusy(true); setStatus(null); try { await authenticatedFetch('/api/support', { method: 'POST', body: JSON.stringify({ kind, message }) }).then(readJson); setMessage(''); setModal(null); setStatus('Message saved successfully.'); } catch (e) { setStatus(e instanceof Error ? e.message : 'Unable to send message'); } finally { setBusy(false); } };
  const deactivate = async () => { setBusy(true); try { if (!isDemo) await authenticatedFetch('/api/account', { method: 'PATCH', body: JSON.stringify({ action: 'deactivate' }) }).then(readJson); if (isDemo || !auth) logoutDemo(); else await signOut(auth); window.location.href = '/'; } finally { setBusy(false); } };
  const removeAccount = async () => { setBusy(true); setStatus(null); try { if (isDemo || !auth?.currentUser) { logoutDemo(); return; } await authenticatedFetch('/api/account', { method: 'DELETE' }).then(readJson); await deleteUser(auth.currentUser); window.location.href = '/'; } catch (e) { setStatus(e instanceof Error ? e.message : 'Account deletion failed. You may need to sign in again before deleting your Firebase account.'); } finally { setBusy(false); } };
  const unblock = async (targetUserId: string) => { await authenticatedFetch('/api/blocks', { method: 'DELETE', body: JSON.stringify({ targetUserId }) }).then(readJson); await loadBlocks(); };
  return <div className="ss-page ss-page-pad space-y-8 lg:space-y-10"><section><p className="text-[10px] uppercase tracking-[0.17em] text-muted-foreground font-bold">Preferences</p><h1 className="mt-3">Settings.</h1><p className="mt-3 max-w-xl text-sm text-muted-foreground">Account lifecycle, support and safety actions now persist through authenticated server routes.</p>{status && <p role="status" className="mt-3 text-xs text-muted-foreground">{status}</p>}</section>
    <section className="grid lg:grid-cols-2 gap-8 lg:gap-12"><SettingsGroup label="Support" title="Help & feedback"><Row icon={Bug} title="Report a bug" copy="Persist a reproducible issue for review." onClick={() => setModal('bug')} /><Row icon={Mail} title="Contact developers" copy="Send product feedback or a feature request." onClick={() => setModal('contact')} /></SettingsGroup><SettingsGroup label="Safety" title="Privacy controls"><Row icon={Ban} title="Blocked users" copy="Manage persistent user blocks." onClick={() => setModal('blocked')} trailing={String(blocks.length)} /><div className="min-h-[78px] py-4 flex items-center gap-4"><span className="h-11 w-11 rounded-full bg-muted grid place-items-center"><Shield className="h-4 w-4" /></span><div className="flex-1"><h3 className="text-xs font-extrabold">Session safety</h3><p className="mt-1 text-[11px] text-muted-foreground">Live calls use explicit check-ins and user reports. No simulated AI identity check is advertised.</p></div></div></SettingsGroup></section>
    <section><div className="pb-3 border-b border-red-500/25"><p className="text-[10px] uppercase tracking-[0.14em] text-red-500 font-bold">Account actions</p><h2 className="mt-1">Danger zone</h2></div><div className="divide-y divide-[var(--hairline)] border-b ss-hairline"><Row icon={PauseCircle} title="Deactivate account" copy="Hide your profile from matching and sign out." onClick={() => setModal('deactivate')} /><Row icon={Trash2} title="Delete account" copy="Delete application data, then remove the authentication account." onClick={() => setModal('delete')} danger /></div></section>
    <AccessibleSheet open={modal === 'bug' || modal === 'contact'} onClose={() => setModal(null)} title={modal === 'bug' ? 'Report a bug' : 'Contact developers'}><textarea value={message} onChange={(e)=>setMessage(e.target.value)} className="ss-input min-h-36 py-3" placeholder={modal === 'bug' ? 'What happened, and what did you expect?' : 'Your message'} /><button disabled={busy || message.trim().length < 2} onClick={() => submitSupport(modal === 'bug' ? 'bug' : 'contact')} className="ss-button-primary w-full mt-3 disabled:opacity-50">{busy ? 'Sending…' : 'Send message'}</button></AccessibleSheet>
    <AccessibleSheet open={modal === 'blocked'} onClose={() => setModal(null)} title="Blocked users" description="Blocked users are excluded from matching and messaging.">{blocks.length ? <div className="divide-y divide-[var(--hairline)]">{blocks.map((block) => <div key={block.id} className="min-h-14 flex items-center gap-3"><span className="h-10 w-10 rounded-full bg-muted grid place-items-center font-bold">{(block.display_name||'U').slice(0,2).toUpperCase()}</span><span className="flex-1 text-xs font-bold">{block.display_name || 'Skill Swap user'}</span><button onClick={() => unblock(block.id)} className="ss-button-secondary">Unblock</button></div>)}</div> : <p className="py-8 text-center text-xs text-muted-foreground">No blocked users.</p>}</AccessibleSheet>
    <AccessibleSheet open={modal === 'deactivate'} onClose={() => setModal(null)} title="Deactivate account?" description="Your profile will stop appearing in discovery until you sign in and reactivate it."><div className="p-4 border ss-hairline rounded-[9px] bg-muted/30"><AlertTriangle className="h-5 w-5" /><p className="mt-2 text-xs text-muted-foreground">Existing messages remain for conversation integrity, but matching excludes inactive profiles.</p></div><button disabled={busy} onClick={deactivate} className="ss-button-primary w-full mt-4">{busy ? 'Working…' : 'Deactivate & sign out'}</button></AccessibleSheet>
    <AccessibleSheet open={modal === 'delete'} onClose={() => setModal(null)} title="Delete account?" description="This action removes your Skill Swap application data and then your Firebase authentication account."><div className="p-4 border border-red-500/30 rounded-[9px] bg-red-500/5"><AlertTriangle className="h-5 w-5 text-red-500" /><p className="mt-2 text-xs text-muted-foreground">This action cannot be undone.</p></div><button disabled={busy} onClick={removeAccount} className="min-h-11 w-full mt-4 rounded-[9px] bg-red-500 text-white text-xs font-bold">{busy ? 'Deleting…' : 'Delete permanently'}</button></AccessibleSheet>
  </div>;
}
function SettingsGroup({ label, title, children }: { label: string; title: string; children: React.ReactNode }) { return <div><div className="pb-3 border-b ss-hairline"><p className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground font-bold">{label}</p><h2 className="mt-1">{title}</h2></div><div className="divide-y divide-[var(--hairline)] border-b ss-hairline">{children}</div></div>; }
function Row({ icon: Icon, title, copy, onClick, trailing, danger = false }: { icon: typeof Bug; title: string; copy: string; onClick: () => void; trailing?: string; danger?: boolean }) { return <button onClick={onClick} className="w-full min-h-[78px] py-4 flex items-center gap-4 text-left hover:bg-muted/45"><span className={`h-11 w-11 rounded-full grid place-items-center ${danger ? 'bg-red-500/10 text-red-500' : 'bg-muted'}`}><Icon className="h-4 w-4" /></span><span className="flex-1"><span className={`block text-xs font-extrabold ${danger ? 'text-red-500' : ''}`}>{title}</span><span className="block mt-1 text-[11px] text-muted-foreground">{copy}</span></span>{trailing && <span className="ss-chip">{trailing}</span>}</button>; }
