'use client';

import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { BarChart3, Bell, ChevronRight, Home, LogOut, Map, Menu, MessageSquare, Moon, PhoneCall, Settings, Sun, UserRound, Users } from 'lucide-react';
import { signOut } from 'next-auth/react';
import { useEffect, useMemo, useState } from 'react';
import { useTheme } from 'next-themes';
import { AccessibleSheet } from '@/components/ui/AccessibleSheet';
import { useAuth } from '@/context/AuthContext';
import { authenticatedFetch, readJson } from '@/lib/api';

const primaryNav = [
  { name: 'Home', href: '/dashboard', icon: Home }, { name: 'Matches', href: '/dashboard/matches', icon: Users }, { name: 'Roadmap', href: '/dashboard/roadmap', icon: Map }, { name: 'Messages', href: '/dashboard/messages', icon: MessageSquare }, { name: 'Analytics', href: '/dashboard/analytics', icon: BarChart3 },
];
const quickLaunch = [
  { name: 'Start call', href: '/dashboard/call', icon: PhoneCall }, { name: 'Find a match', href: '/dashboard/matches', icon: Users }, { name: 'Build roadmap', href: '/dashboard/roadmap', icon: Map }, { name: 'Open messages', href: '/dashboard/messages', icon: MessageSquare }, { name: 'Profile', href: '/dashboard/profile', icon: UserRound }, { name: 'Settings', href: '/dashboard/settings', icon: Settings },
];
type Notification = { id: string; type: string; payload: Record<string, unknown>; read_at: string | null; created_at: string };

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  const { user, loading } = useAuth(); const pathname = usePathname(); const router = useRouter(); const { resolvedTheme, setTheme } = useTheme();
  const [mounted, setMounted] = useState(false); const [showMore, setShowMore] = useState(false); const [showNotifications, setShowNotifications] = useState(false); const [showLogout, setShowLogout] = useState(false); const [showOnboarding, setShowOnboarding] = useState(false); const [notifications, setNotifications] = useState<Notification[]>([]); const [unread, setUnread] = useState(0);
  useEffect(() => { setMounted(true); if (!loading && !user) router.replace('/auth/signin'); }, [loading, user, router]);
  useEffect(() => { if (!user) return; let active = true; const load = async () => { try { const [profileData, notificationData] = await Promise.all([authenticatedFetch('/api/profile').then((r) => readJson<{ profile: { skills: unknown[] } }>(r)), authenticatedFetch('/api/notifications').then((r) => readJson<{ notifications: Notification[]; unread: number }>(r))]); if (!active) return; setShowOnboarding((profileData.profile.skills?.length ?? 0) === 0); setNotifications(notificationData.notifications); setUnread(notificationData.unread); } catch {} }; void load(); const timer = window.setInterval(() => void authenticatedFetch('/api/notifications').then((r) => readJson<{ notifications: Notification[]; unread: number }>(r)).then((data) => { if (active) { setNotifications(data.notifications); setUnread(data.unread); } }).catch(() => undefined), 10000); return () => { active = false; clearInterval(timer); }; }, [user?.uid]);
  const pageTitle = useMemo(() => pathname === '/dashboard' ? 'Home' : primaryNav.find((item) => item.href === pathname)?.name || pathname.split('/').filter(Boolean).pop()?.replaceAll('-', ' ') || 'Dashboard', [pathname]);
  if (loading || !user || !mounted) return <div className="min-h-[100dvh] grid place-items-center bg-background"><div className="h-7 w-7 rounded-full border-2 border-border border-t-[var(--signal)] animate-spin" aria-label="Loading" /></div>;
  const handleLogout = async () => { setShowLogout(false); await signOut({ callbackUrl: '/' }); };
  const markAllRead = async () => { await authenticatedFetch('/api/notifications', { method: 'PATCH', body: JSON.stringify({ all: true }) }).then(readJson); setNotifications((current) => current.map((item) => ({ ...item, read_at: new Date().toISOString() }))); setUnread(0); };

  return <div data-dashboard-shell className="min-h-[100dvh] bg-background text-foreground lg:flex">
    <aside className="ss-desktop-only sticky top-0 h-[100dvh] w-[240px] shrink-0 border-r ss-hairline bg-[var(--sidebar)]"><div className="h-full flex flex-col"><div className="h-16 flex items-center px-5 border-b ss-hairline"><Link href="/dashboard" className="flex items-center gap-3 min-h-11"><span className="ss-chamfer h-8 w-8 grid place-items-center bg-[var(--signal)] text-black font-black text-sm">S</span><span className="text-[15px] font-extrabold tracking-[-0.03em]">Skill Swap</span></Link></div><nav className="p-3 flex-1 overflow-y-auto"><p className="px-3 pt-2 pb-3 text-[10px] tracking-[0.16em] uppercase text-muted-foreground font-bold">Workspace</p><div className="space-y-1">{primaryNav.map((item) => { const active = pathname === item.href; return <Link key={item.href} href={item.href} className={`relative min-h-11 flex items-center gap-3 px-3 rounded-[8px] text-[13px] font-semibold ${active ? 'bg-foreground text-background' : 'text-muted-foreground hover:text-foreground hover:bg-muted'}`}>{active && <span className="absolute left-0 top-2 bottom-2 w-[3px] bg-[var(--signal)] rounded-r-full" />}<item.icon className="h-[17px] w-[17px]" /><span>{item.name}</span></Link>; })}</div><p className="px-3 mt-7 pb-3 text-[10px] tracking-[0.16em] uppercase text-muted-foreground font-bold">Quick launch</p>{quickLaunch.slice(0,4).map((item)=><Link key={item.href} href={item.href} className="min-h-11 flex items-center gap-3 px-3 rounded-[8px] text-xs text-muted-foreground hover:text-foreground hover:bg-muted"><item.icon className="h-4 w-4" />{item.name}</Link>)}</nav><div className="p-3 border-t ss-hairline"><Link href="/dashboard/profile" className="min-h-11 flex items-center gap-3 px-3 rounded-[8px] hover:bg-muted"><span className="h-8 w-8 rounded-full bg-[var(--signal)] text-black grid place-items-center font-extrabold text-xs">{(user.displayName||user.email||'U').charAt(0).toUpperCase()}</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-bold">{user.displayName || 'Skill Swap user'}</span><span className="block truncate text-[10px] text-muted-foreground">{user.email || 'Google account'}</span></span><ChevronRight className="h-4 w-4 text-muted-foreground" /></Link><div className="mt-1 grid grid-cols-2 gap-1"><button onClick={()=>setTheme(resolvedTheme==='dark'?'light':'dark')} className="min-h-11 px-3 flex items-center gap-2 rounded-[8px] text-xs text-muted-foreground hover:bg-muted">{resolvedTheme==='dark'?<Sun className="h-4 w-4"/>:<Moon className="h-4 w-4"/>} Theme</button><button onClick={()=>setShowLogout(true)} className="min-h-11 px-3 flex items-center gap-2 rounded-[8px] text-xs text-muted-foreground hover:text-red-500"><LogOut className="h-4 w-4"/> Sign out</button></div></div></div></aside>
    <section className="min-w-0 flex-1 min-h-[100dvh]"><header className="sticky top-0 z-40 h-14 lg:h-16 flex items-center justify-between px-4 lg:px-7 border-b ss-hairline bg-background/95 backdrop-blur-xl"><div className="flex items-center gap-3 min-w-0"><Link href="/dashboard" className="lg:hidden ss-chamfer h-8 w-8 grid place-items-center bg-[var(--signal)] text-black font-black">S</Link><div><p className="hidden sm:block text-[10px] uppercase tracking-[0.14em] text-muted-foreground font-bold">Workspace</p><h2 className="text-[15px] lg:text-[16px] font-extrabold capitalize truncate">{pageTitle}</h2></div></div><div className="flex items-center gap-1"><button onClick={()=>setTheme(resolvedTheme==='dark'?'light':'dark')} className="min-h-11 min-w-11 grid place-items-center rounded-full hover:bg-muted" aria-label="Toggle theme">{resolvedTheme==='dark'?<Sun className="h-[18px] w-[18px]"/>:<Moon className="h-[18px] w-[18px]"/>}</button><button onClick={()=>setShowNotifications(true)} className="relative min-h-11 min-w-11 grid place-items-center rounded-full hover:bg-muted" aria-label={`Notifications${unread ? `, ${unread} unread` : ''}`}><Bell className="h-[18px] w-[18px]" />{unread>0&&<span className="absolute top-[8px] right-[8px] h-2.5 w-2.5 rounded-full bg-[var(--signal)] ring-2 ring-background" />}</button><button onClick={()=>setShowMore(true)} className="lg:hidden min-h-11 min-w-11 grid place-items-center rounded-full hover:bg-muted" aria-label="Open quick actions"><Menu className="h-[19px] w-[19px]" /></button></div></header><main className="ss-bottom-safe lg:pb-0"><div className="lg:hidden px-4 pt-3 border-b ss-hairline"><div className="ss-chip-rail">{quickLaunch.slice(0,4).map((item)=><Link key={item.href} href={item.href} className="ss-chip"><item.icon className="h-3.5 w-3.5" />{item.name}</Link>)}</div></div>{children}</main></section>
    <nav className="lg:hidden fixed bottom-0 inset-x-0 z-50 border-t ss-hairline bg-background/96 backdrop-blur-xl pb-[env(safe-area-inset-bottom)]"><div className="grid grid-cols-5 h-[66px]">{primaryNav.slice(0,4).map((item)=>{const active=pathname===item.href; return <Link key={item.href} href={item.href} className={`relative min-h-11 flex flex-col items-center justify-center gap-1 text-[10px] font-bold ${active?'text-foreground':'text-muted-foreground'}`}>{active&&<span className="absolute top-0 h-[3px] w-7 rounded-b-full bg-[var(--signal)]"/>}<item.icon className="h-[19px] w-[19px]"/><span>{item.name}</span></Link>})}<button onClick={()=>setShowMore(true)} className="min-h-11 flex flex-col items-center justify-center gap-1 text-[10px] font-bold text-muted-foreground"><Menu className="h-[19px] w-[19px]"/><span>More</span></button></div></nav>
    <AccessibleSheet open={showMore} onClose={()=>setShowMore(false)} title="Quick launch"><div className="grid grid-cols-2 gap-px bg-[var(--hairline)] border ss-hairline">{quickLaunch.map((item)=><Link key={item.href} href={item.href} onClick={()=>setShowMore(false)} className="min-h-[92px] bg-[var(--canvas-elevated)] p-4 flex flex-col justify-between"><item.icon className="h-5 w-5"/><span className="text-xs font-bold">{item.name}</span></Link>)}</div></AccessibleSheet>
    <AccessibleSheet open={showNotifications} onClose={()=>setShowNotifications(false)} title="Notifications"><div className="flex justify-end"><button disabled={!unread} onClick={markAllRead} className="ss-button-secondary">Mark all read</button></div><div className="mt-3 divide-y divide-[var(--hairline)] border-y ss-hairline">{notifications.length ? notifications.map((notification)=><div key={notification.id} className="py-3"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${notification.read_at?'bg-muted-foreground/30':'bg-[var(--signal)]'}`}/><p className="text-xs font-bold">{notificationLabel(notification.type)}</p></div><p className="mt-1 pl-4 text-[10px] text-muted-foreground">{new Date(notification.created_at).toLocaleString()}</p></div>) : <p className="py-8 text-center text-xs text-muted-foreground">No notifications yet.</p>}</div></AccessibleSheet>
    <AccessibleSheet open={showLogout} onClose={()=>setShowLogout(false)} title="Sign out?" description="You can sign back in with Google at any time."><div className="grid grid-cols-2 gap-2"><button onClick={()=>setShowLogout(false)} className="ss-button-secondary">Cancel</button><button onClick={handleLogout} className="ss-button-primary">Sign out</button></div></AccessibleSheet>
    <AccessibleSheet open={showOnboarding} onClose={()=>setShowOnboarding(false)} title="Complete your profile" description="Add at least one teach or learn skill so reciprocal matching can work."><Link href="/dashboard/profile" onClick={()=>setShowOnboarding(false)} className="ss-button-primary w-full">Open profile <ChevronRight className="h-4 w-4" /></Link></AccessibleSheet>
  </div>;
}
function notificationLabel(type: string) { if (type === 'match_request') return 'New match request'; if (type === 'match_accepted') return 'Match accepted'; if (type === 'message') return 'New message'; return type.replaceAll('_',' '); }
